// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lirhguhjajxxjnepvufz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpcmhndWhqYWp4eGpuZXB2dWZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjQ0MTgsImV4cCI6MjA2MDc0MDQxOH0.tylMIPqoIs0MbH0pS4ZiHydCQ3aVDStCOkr8tlPb_ks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);